### ISSUE TITLE
Running it the easy way, doesn't appear to work.

### ISSUE THREAD

**Issue by supertick** [dheera/rosboard#126]
Cool project.  Browser can attach, websockets seem fine, but the subscribe appears to explode using the run script.
Exception below

System:
Ubuntu 22.04
ros2 humble

Cheers

[INFO] [1718838209.987495459] [rosboard_node]: Subscribing to /clock

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'Unknown QoS history policy, at ./src/qos.cpp:61'

with this new error message:

  'create_publisher() failed setting topic QoS, at ./src/subscription.cpp:221'

rcutils_reset_error() should be called after error handling to avoid this.
<<<

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'create_publisher() failed setting topic QoS, at ./src/subscription.cpp:221, at ./src/rcl/subscription.c:109'

with this new error message:

  'invalid allocator, at ./src/rcl/subscription.c:219'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
invalid allocator, at ./src/rcl/subscription.c:219
dmesg: read kernel buffer failed: Operation not permitted
[WARN] [1718838210.018317523] [rosboard_node]: Failed to create subscription: invalid allocator, at ./src/rcl/subscription.c:219
Traceback (most recent call last):
  File "/home/gperry/github/rosboard/rosboard/rosboard.py", line 261, in sync_subs
    self.local_subs[topic_name] = rospy.Subscriber(
  File "/home/gperry/github/rosboard/rosboard/rospy2/__init__.py", line 225, in __init__
    self._sub = _node.create_subscription(topic_type, topic_name, self._ros2_callback, qos, event_callbacks = rclpy.qos_event.SubscriptionEventCallbacks())
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 1370, in create_subscription
    subscription_object = _rclpy.Subscription(
rclpy._rclpy_pybind11.RCLError: Failed to create subscription: invalid allocator, at ./src/rcl/subscription.c:219
Exception ignored in: <function Subscriber.__del__ at 0x7ce5c8a82e60>
Traceback (most recent call last):
  File "/home/gperry/github/rosboard/rosboard/rospy2/__init__.py", line 231, in __del__
    _node.destroy_subscription(self._sub)
AttributeError: 'Subscriber' object has no attribute '_sub'
[INFO] [1718838210.027604725] [rosboard_node]: Subscribing to /clock

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'Unknown QoS history policy, at ./src/qos.cpp:61'

with this new error message:

  'create_publisher() failed setting topic QoS, at ./src/subscription.cpp:221'

rcutils_reset_error() should be called after error handling to avoid this.
<<<

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'create_publisher() failed setting topic QoS, at ./src/subscription.cpp:221, at ./src/rcl/subscription.c:109'

with this new error message:

  'invalid allocator, at ./src/rcl/subscription.c:219'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
invalid allocator, at ./src/rcl/subscription.c:219
[WARN] [1718838210.050833275] [rosboard_node]: Failed to create subscription: invalid allocator, at ./src/rcl/subscription.c:219
Traceback (most recent call last):
  File "/home/gperry/github/rosboard/rosboard/rosboard.py", line 261, in sync_subs
    self.local_subs[topic_name] = rospy.Subscriber(
  File "/home/gperry/github/rosboard/rosboard/rospy2/__init__.py", line 225, in __init__
    self._sub = _node.create_subscription(topic_type, topic_name, self._ros2_callback, qos, event_callbacks = rclpy.qos_event.SubscriptionEventCallbacks())
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 1370, in create_subscription
    subscription_object = _rclpy.Subscription(
rclpy._rclpy_pybind11.RCLError: Failed to create subscription: invalid allocator, at ./src/rcl/subscription.c:219
Exception ignored in: <function Subscriber.__del__ at 0x7ce5c8a82e60>
Traceback (most recent call last):
  File "/home/gperry/github/rosboard/rosboard/rospy2/__init__.py", line 231, in __del__
    _node.destroy_subscription(self._sub)
AttributeError: 'Subscriber' object has no attribute '_sub'
[INFO] [1718838210.063940514] [rosboard_node]: Subscribing to /clock

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()

**Comment by supertick** [comment]
I can try installing as package, but  my guess of the root cause is a change in ros2 qos policy your rospy2 is not yet handling ?
Just a guess.

**Comment by dheera** [comment]
Hi, can you try the [release](https://github.com/dheera/rosboard/tree/release) branch while I look into this?

**Comment by supertick** [comment]
Thanks for the quick reply,  yes release branch works :+1:

**Comment by dheera** [comment]
Hi,
I merged a PR into the main branch that should make it work. Let me know if it works for you!

**Comment by dheera** [comment]
(Please re-open if still an issue)
